# Generated by Django 3.2 on 2021-12-24 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('production', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=50)),
                ('value_direction', models.CharField(max_length=50)),
                ('value_selection', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stock_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.stockstrategy')),
            ],
        ),
    ]
