# Generated by Django 3.0.6 on 2021-12-14 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategycriteria',
            name='stock_strategy',
            field=models.ForeignKey(default=199, on_delete=django.db.models.deletion.CASCADE, to='strategy.StockStrategy'),
            preserve_default=False,
        ),
    ]
