# Generated by Django 3.0.6 on 2021-12-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_strategycriteria_stock_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstrategy',
            name='production',
            field=models.BooleanField(default=False),
        ),
    ]
