
DIRECTION_ABOVE = "ABOVE"
DIRECTION_UNDER = "UNDER"
DIRECTION_EQUAL = "EQUAL"

CHANGE_PERCENT = "CHANGE_PERCENT"


# TODO

POSITIVE_PERIOD = "POSITIVE_PERIOD"
POSITIVE_DAYS_ABOVE_NEGATIVE_DAYS = "POSITIVE_DAYS_ABOVE_NEGATIVE_DAYS"
LOW_HIGH_RATION = "LOW_HIGH_RATION"

CURRENT_WAVE_POSITIVE = "CURRENT_WAVE_POSITIVE"
CURRENT_WAVE_ABOVE_AVG_POSITIVE_LENGTH = "CURRENT_WAVE_ABOVE_AVG_POSITIVE_LENGTH"



CURRENT_WAVE_NEGATIVE = "CURRENT_WAVE_NEGATIVE"
CURRENT_WAVE_ABOVE_AVG_NEGATIVE_LENGTH = "CURRENT_WAVE_ABOVE_AVG_NEGATIVE_LENGTH"