# Generated by Django 3.0.6 on 2021-12-14 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradesuiteevent',
            name='created_date',
        ),
        migrations.AddField(
            model_name='tradesuiteevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradesuiteevent',
            name='name',
            field=models.CharField(default='Automatic trade event', max_length=30),
        ),
    ]
