# Generated by Django 3.2 on 2021-12-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20211214_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesuiteevent',
            name='custom_date',
            field=models.CharField(default='Date to compare with', max_length=50),
        ),
    ]
