# Generated by Django 3.2 on 2021-12-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_tcorescheduler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scheduler',
        ),
        migrations.DeleteModel(
            name='TCoreScheduler',
        ),
        migrations.RemoveField(
            model_name='tradesuiteevent',
            name='custom_date',
        ),
        migrations.AddField(
            model_name='tradesuiteevent',
            name='custom_full',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tradesuiteevent',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tradesuiteevent',
            name='time_completed',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tradesuiteevent',
            name='time_started',
            field=models.CharField(default='', max_length=50),
        ),
    ]
