# Generated by Django 3.2 on 2021-12-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20211229_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesuiteevent',
            name='error',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='tradesuiteevent',
            name='result',
            field=models.CharField(default='', max_length=50),
        ),
    ]
