# Generated by Django 3.2 on 2021-12-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20211230_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesuiteevent',
            name='number_of_stocks',
            field=models.FloatField(default=0),
        ),
    ]
