# Generated by Django 3.2 on 2021-12-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_tradesuiteevent_number_of_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesuiteevent',
            name='number_of_trades',
            field=models.FloatField(default=0),
        ),
    ]
