# Generated by Django 3.2 on 2021-12-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_tradesuiteevent_number_of_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesuiteevent',
            name='test_mode',
            field=models.BooleanField(default=True),
        ),
    ]
