# Generated by Django 3.2 on 2022-01-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_tradesuiteevent_test_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradesuiteevent',
            old_name='number_of_trades',
            new_name='number_of_buy_transactions',
        ),
        migrations.AddField(
            model_name='tradesuiteevent',
            name='number_of_orders',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tradesuiteevent',
            name='number_of_sell_transactions',
            field=models.FloatField(default=0),
        ),
    ]
