# Generated by Django 3.2 on 2022-01-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_tradesuiteevent_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradesuiteevent',
            old_name='date',
            new_name='date_started',
        ),
        migrations.RemoveField(
            model_name='tradesuiteevent',
            name='custom_full',
        ),
        migrations.RemoveField(
            model_name='tradesuiteevent',
            name='time_completed',
        ),
        migrations.AddField(
            model_name='tradesuiteevent',
            name='time_completed_st',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tradesuiteevent',
            name='time_started_st',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
