# Generated by Django 3.2 on 2022-01-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20220103_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesuiteevent',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
