# Generated by Django 3.2 on 2022-01-04 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_tradesuiteevent_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradesuiteevent',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='tradesuiteevent',
            name='time_completed_st',
        ),
        migrations.RemoveField(
            model_name='tradesuiteevent',
            name='time_started',
        ),
        migrations.RemoveField(
            model_name='tradesuiteevent',
            name='time_started_st',
        ),
    ]
