# Generated by Django 3.2 on 2021-12-24 22:42

from django.db import migrations, models
import django.db.models.deletion
import order.lib.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=order.lib.constants.Transactions['ACTIVE'], max_length=30)),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('order_id', models.CharField(blank=True, max_length=30)),
                ('stop_loss_id', models.CharField(blank=True, max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=order.lib.constants.Transactions['ACTIVE'], max_length=30)),
                ('price', models.FloatField(blank=True, default=None)),
                ('amount', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('order_id', models.CharField(blank=True, max_length=30)),
                ('stop_loss_id', models.CharField(blank=True, max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('asset_ticker', models.CharField(max_length=30)),
                ('completed', models.DateTimeField(auto_now_add=True)),
                ('production', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buy_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.buytransaction')),
            ],
        ),
    ]
