# Generated by Django 3.2 on 2021-12-30 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buytransaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='selltransaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='selltransaction',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='selltransaction',
            name='take_profit',
        ),
        migrations.AddField(
            model_name='order',
            name='lose_stop_loss_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='lose_target',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='profit_stop_loss_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='profit_target',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='sell_transaction',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='order.selltransaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='buy_transaction',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.buytransaction'),
        ),
        migrations.AlterField(
            model_name='selltransaction',
            name='price',
            field=models.FloatField(),
        ),
    ]
