# Generated by Django 3.2 on 2021-12-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dummy',
            field=models.CharField(default='', max_length=50),
        ),
    ]
