# Generated by Django 3.2 on 2021-12-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211230_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buytransaction',
            name='stop_loss_id',
        ),
        migrations.RemoveField(
            model_name='selltransaction',
            name='stop_loss_id',
        ),
    ]
