# Generated by Django 3.2 on 2021-12-30 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211230_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buy_transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.buytransaction'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sell_transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.selltransaction'),
        ),
    ]
