# Generated by Django 3.2 on 2022-01-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20211231_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dummy',
        ),
        migrations.AddField(
            model_name='order',
            name='successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='ONGOING', max_length=30),
        ),
    ]
