# Generated by Django 3.2 on 2022-01-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20220102_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_of_buy_transactions',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_sell_transactions',
            field=models.FloatField(default=0),
        ),
    ]
