# Generated by Django 3.2 on 2021-12-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
        ('order', '0005_alter_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='strategy',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='strategy.stockstrategy'),
            preserve_default=False,
        ),
    ]
