# Generated by Django 3.2 on 2021-12-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_strategy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='order_completed',
        ),
    ]
