# Generated by Django 3.2 on 2022-01-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20220102_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number_of_buy_transactions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number_of_sell_transactions',
        ),
    ]
