# Generated by Django 3.2 on 2021-12-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_completed_order_order_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_completed',
        ),
    ]
